- name: nginx install and run
  hosts: frontend
  become: yes # sudo access
  tasks:
    - name: install nginx server
      ansible.builtin.package:
        name: nginx
        state: present

    - name: start nginx
      ansible.builtin.service:
        name: nginx
        state: started
<<<<<<< HEAD
        enabled: yes
=======
        enabled: yes
>>>>>>> 2299619583dae1637577eea8465957a9aee5151f
