- name: play level variables
  hosts: local
  connection: local
  vars:
    COURSE: Ansible # equal to COURSE=Ansible in shell, shell we refer $VAR or ${VAR}
    DURATION: 10hr
    TRAINER: Rama
  tasks:
    - name: print course information
      ansible.builtin.debug:
        msg: "HELLO {{COURSE}},  CourseDuration: {{DURATION}}, Trainer is {{Rama}}"