- name: play level variables
  hosts: localhost
  connection: local
  vars:
    COURSE: Ansible # equal to COURSE=Ansible in shell, shell we refer $VAR or ${VAR}
    DURATION: 10hr
    TRAINER: Rama
  tasks:
    - name: print course information
      ansible.builtin.debug:
      #vars reference should be surrounded by ""
<<<<<<< HEAD
        msg: "HELLO {{COURSE}},  CourseDuration: {{DURATION}}, Trainer is: {{TRAINER}}"
=======
        msg: "HELLO {{COURSE}},  CourseDuration: {{DURATION}}, Trainer is: {{TRAINER}}"
>>>>>>> 2299619583dae1637577eea8465957a9aee5151f
