- name: variables from prompt
  hosts: localhost
  connection: local
  vars_prompt:
  - name: USERNAME
    prompt: Please enter your username
    private: true
  
  - name: PASSWORD
    prompt: please enter your password
    private: true
  tasks:
  - name: printing user information
    ansible.builtin.debug:
<<<<<<< HEAD
      msg: " Hello username is: {{USERNAME}} and password is: {{PASSWORD}}"

      
=======
      msg: "Hello Username is: {{ USERNAME }}, password is: {{ PASSWORD }}"
>>>>>>> 6001649d64a036901cafe853ea4fbb9624b31f53
